export const CREATE_TERM_REQUEST = "CREATE_TERM_REQUEST";
export const CREATE_TERM_SUCCESS = "CREATE_TERM_SUCCESS";
export const CREATE_TERM_FAILURE = "CREATE_TERM_FAILURE";

export const GET_TERM_REQUEST = "GET_TERM_REQUEST";
export const GET_TERM_SUCCESS = "GET_TERM_SUCCESS";
export const GET_TERM_FAILURE = "GET_TERM_FAILURE";

export const GET_TERMS_BY_GROUP_ID_REQUEST = "GET_TERMS_BY_GROUP_ID_REQUEST";
export const GET_TERMS_BY_GROUP_ID_SUCCESS = "GET_TERMS_BY_GROUP_ID_SUCCESS";
export const GET_TERMS_BY_GROUP_ID_FAILURE = "GET_TERMS_BY_GROUP_ID_FAILURE";

export const UPDATE_TERM_REQUEST = "UPDATE_TERM_REQUEST";
export const UPDATE_TERM_SUCCESS = "UPDATE_TERM_SUCCESS";
export const UPDATE_TERM_FAILURE = "UPDATE_TERM_FAILURE";

export const DELETE_TERM_REQUEST = "DELETE_TERM_REQUEST";
export const DELETE_TERM_SUCCESS = "DELETE_TERM_SUCCESS";
export const DELETE_TERM_FAILURE = "DELETE_TERM_FAILURE";

