export const CREATE_TERM_REQUEST = "CREATE_TERM_REQUEST";
export const CREATE_TERM_SUCCESS = "CREATE_TERM_SUCCESS";
export const CREATE_TERM_FAILURE = "CREATE_TERM_FAILURE";

export const GET_TERM_REQUEST = "GET_TERM_REQUEST";
export const GET_TERM_SUCCESS = "GET_TERM_SUCCESS";
export const GET_TERM_FAILURE = "GET_TERM_FAILURE";

export const GET_ANSWERS_FOR_TERM_REQUEST = "GET_ANSWERS_FOR_TERM_REQUEST";
export const GET_ANSWERS_FOR_TERM_SUCCESS = "GET_ANSWERS_FOR_TERM_SUCCESS";
export const GET_ANSWERS_FOR_TERM_FAILURE = "GET_ANSWERS_FOR_TERM_FAILURE";

export const GET_TERMS_BY_GROUP_ID_REQUEST = "GET_TERMS_BY_GROUP_ID_REQUEST";
export const GET_TERMS_BY_GROUP_ID_SUCCESS = "GET_TERMS_BY_GROUP_ID_SUCCESS";
export const GET_TERMS_BY_GROUP_ID_FAILURE = "GET_TERMS_BY_GROUP_ID_FAILURE";

export const UPDATE_TERM_REQUEST = "UPDATE_TERM_REQUEST";
export const UPDATE_TERM_SUCCESS = "UPDATE_TERM_SUCCESS";
export const UPDATE_TERM_FAILURE = "UPDATE_TERM_FAILURE";

export const DELETE_TERM_REQUEST = "DELETE_TERM_REQUEST";
export const DELETE_TERM_SUCCESS = "DELETE_TERM_SUCCESS";
export const DELETE_TERM_FAILURE = "DELETE_TERM_FAILURE";

export const GET_STUDY_SET_REQUEST = "GET_STUDY_SET_REQUEST";
export const GET_STUDY_SET_SUCCESS = "GET_STUDY_SET_SUCCESS";
export const GET_STUDY_SET_FAILURE = "GET_STUDY_SET_FAILURE";

export const GET_STUDY_SET_WITH_KEYWORDS_REQUEST = "GET_STUDY_SET_WITH_KEYWORDS_REQUEST";
export const GET_STUDY_SET_WITH_KEYWORDS_SUCCESS = "GET_STUDY_SET_WITH_KEYWORDS_SUCCESS";
export const GET_STUDY_SET_WITH_KEYWORDS_FAILURE = "GET_STUDY_SET_WITH_KEYWORDS_FAILURE";

export const GET_STUDY_SET_WITH_IMAGES_REQUEST = "GET_STUDY_SET_WITH_IMAGES_REQUEST";
export const GET_STUDY_SET_WITH_IMAGES_SUCCESS = "GET_STUDY_SET_WITH_IMAGES_SUCCESS";
export const GET_STUDY_SET_WITH_IMAGES_FAILURE = "GET_STUDY_SET_WITH_IMAGES_FAILURE";

export const UPDATE_TERM_AWARE_STATUS_REQUEST = "UPDATE_TERM_AWARE_STATUS_REQUEST";
export const UPDATE_TERM_AWARE_STATUS_SUCCESS = "UPDATE_TERM_AWARE_STATUS_SUCCESS";
export const UPDATE_TERM_AWARE_STATUS_FAILURE = "UPDATE_TERM_AWARE_STATUS_FAILURE";

export const RESET_GROUP_TERMS_AWARE_STATUS_REQUEST = "RESET_GROUP_TERMS_AWARE_STATUS_REQUEST";
export const RESET_GROUP_TERMS_AWARE_STATUS_SUCCESS = "RESET_GROUP_TERMS_AWARE_STATUS_SUCCESS";
export const RESET_GROUP_TERMS_AWARE_STATUS_FAILURE = "RESET_GROUP_TERMS_AWARE_STATUS_FAILURE";

export const SET_STUDY_MODE = "SET_STUDY_MODE";

export const FINISH_STUDYING = "FINISH_STUDYING";
