export const CREATE_TERM_GROUP_FOR_USER_REQUEST = "CREATE_TERM_GROUP_FOR_USER_REQUEST";
export const CREATE_TERM_GROUP_FOR_USER_SUCCESS = "CREATE_TERM_GROUP_FOR_USER_SUCCESS";
export const CREATE_TERM_GROUP_FOR_USER_FAILURE = "CREATE_TERM_GROUP_FOR_USER_FAILURE";

export const CREATE_TERM_GROUP_FOR_FOLDER_REQUEST = "CREATE_TERM_GROUP_FOR_FOLDER_REQUEST";
export const CREATE_TERM_GROUP_FOR_FOLDER_SUCCESS = "CREATE_TERM_GROUP_FOR_FOLDER_SUCCESS";
export const CREATE_TERM_GROUP_FOR_FOLDER_FAILURE = "CREATE_TERM_GROUP_FOR_FOLDER_FAILURE";

export const GET_TERM_GROUPS_BY_USER_ID_REQUEST = "GET_TERM_GROUPS_BY_USER_ID_REQUEST";
export const GET_TERM_GROUPS_BY_USER_ID_SUCCESS = "GET_TERM_GROUPS_BY_USER_ID_SUCCESS";
export const GET_TERM_GROUPS_BY_USER_ID_FAILURE = "GET_TERM_GROUPS_BY_USER_ID_FAILURE";

export const GET_TERM_GROUPS_BY_FOLDER_ID_REQUEST = "GET_TERM_GROUPS_BY_FOLDER_ID_REQUEST";
export const GET_TERM_GROUPS_BY_FOLDER_ID_SUCCESS = "GET_TERM_GROUPS_BY_FOLDER_ID_SUCCESS";
export const GET_TERM_GROUPS_BY_FOLDER_ID_FAILURE = "GET_TERM_GROUPS_BY_FOLDER_ID_FAILURE";

export const GET_TERM_GROUP_REQUEST = "GET_TERM_GROUP_REQUEST";
export const GET_TERM_GROUP_SUCCESS = "GET_TERM_GROUP_SUCCESS";
export const GET_TERM_GROUP_FAILURE = "GET_TERM_GROUP_FAILURE";

export const UPDATE_TERM_GROUP_REQUEST = "UPDATE_TERM_GROUP_REQUEST";
export const UPDATE_TERM_GROUP_SUCCESS = "UPDATE_TERM_GROUP_SUCCESS";
export const UPDATE_TERM_GROUP_FAILURE = "UPDATE_TERM_GROUP_FAILURE";

export const DELETE_TERM_GROUP_REQUEST = "DELETE_TERM_GROUP_REQUEST";
export const DELETE_TERM_GROUP_SUCCESS = "DELETE_TERM_GROUP_SUCCESS";
export const DELETE_TERM_GROUP_FAILURE = "DELETE_TERM_GROUP_FAILURE";
