export const CREATE_WORD_SET_REQUEST = "CREATE_WORD_SET_REQUEST";
export const CREATE_WORD_SET_SUCCESS = "CREATE_WORD_SET_SUCCESS";
export const CREATE_WORD_SET_FAILURE = "CREATE_WORD_SET_FAILURE";

export const GET_WORD_SETS_REQUEST = "GET_WORD_SETS_REQUEST";
export const GET_WORD_SETS_SUCCESS = "GET_WORD_SETS_SUCCESS";
export const GET_WORD_SETS_FAILURE = "GET_WORD_SETS_FAILURE";

export const GET_WORD_SET_REQUEST = "GET_WORD_SET_REQUEST";
export const GET_WORD_SET_SUCCESS = "GET_WORD_SET_SUCCESS";
export const GET_WORD_SET_FAILURE = "GET_WORD_SET_FAILURE";

export const DELETE_WORD_SET_REQUEST = "DELETE_WORD_SET_REQUEST";
export const DELETE_WORD_SET_SUCCESS = "DELETE_WORD_SET_SUCCESS";
export const DELETE_WORD_SET_FAILURE = "DELETE_WORD_SET_FAILURE";

export const UPDATE_WORD_SET_REQUEST = "UPDATE_WORD_SET_REQUEST";
export const UPDATE_WORD_SET_SUCCESS = "UPDATE_WORD_SET_SUCCESS";
export const UPDATE_WORD_SET_FAILURE = "UPDATE_WORD_SET_FAILURE";
